name: "HCL AppScan SAST"

on:
  workflow_dispatch:
  pull_request:

permissions:
  checks: write
  pull-requests: write
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Before scan
        run: |
          ls -la
          pwd

      - name: Run AppScan SAST Scan
        id: appscan
        uses: HCL-TECH-SOFTWARE/appscan-sast-action@v1.0.7
        with:
          asoc_key: ${{ secrets.ASOC_KEY }}
          asoc_secret: ${{ secrets.ASOC_SECRET }}
          application_id: ${{ secrets.APP_ID }}
          static_analysis_only: true
          wait_for_analysis: true
          # scan_build_outputs: true
          # fail_for_noncompliance: true
          # failure_threshold: critical

      - name: After scan
        run: |
          ls -la
          pwd

      - name: Salvar log em arquivo
        if: always()
        run: |
         # Captura o log do job atual e salva no arquivo scan.log
         # Usamos o ID do run para garantir que estamos pegando o log certo
          gh run view ${{ github.run_id }} --log > scan.log
          
          # Agora você pode ver o conteúdo do arquivo
          cat scan.log


      # ⬇️ CHECK RUN – visual estilo Orca
      - name: Publish AppScan Security Check
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const jobStatus = '${{ job.status }}';
            const conclusion = jobStatus === 'success' ? 'success' : 'failure';

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'HCL AppScan SAST',
              head_sha: context.sha,
              status: 'completed',
              conclusion: conclusion,
              output: {
                title: 'HCL AppScan SAST – Scan Summary',
                summary: 'Static Application Security Testing completed.',
                text: `
                Severity Findings
               `
              }
            });
